### ISSUE TITLE
# Bug（？）

### ISSUE THREAD

**Issue by mute23-code** [nonebot/adapter-qqguild#16]
在频道中发消息，机器人接收到消息后对频道好友广播了一遍，号秒封
![2c707502bf28772f](https://user-images.githubusercontent.com/110453675/210162977-a7495fca-0a25-4fc8-8f2e-d3665612b067.jpg)

**Comment by yanyongyu** [comment]
你这都不是频道适配器的东西来这发issue干啥，分清楚频道机器人和gocq
