### ISSUE TITLE
配置QQ 频道 协议时遇到如下错误

### ISSUE THREAD

**Issue by Blues-star** [nonebot/adapter-qqguild#2]
ERROR: Could not find a version that satisfies the requirement nonebot-adapter-qqguild (from versions: none)
ERROR: No matching distribution found for nonebot-adapter-qqguild

使用
```
nb adapter install nonebot-adapter-qqguild
```
也不行

**Comment by yanyongyu** [comment]
QQ频道部分因为之前反馈的问题一个多月官方都没能修复，存在一些安全问题，暂时并没有发布

**Comment by Blues-star** [comment]
好的,建议可以在README里说明一下,或者在商店暂时说明一下
