### ISSUE TITLE
可以考虑暴露更多的Api

### ISSUE THREAD

**Issue by XM12G** [nonebot/adapter-qqguild#22]
**我在使用中发现，连post_message这样一个常用的Api也需要call_api才行**

希望开发者可以暴露更多的常用Api给我们

（如果已经有了那当我没说）

**Comment by yanyongyu** [comment]
？？？？？https://v2.nonebot.dev/docs/next/tutorial/call-api#%E8%B0%83%E7%94%A8-api

```python
bot.post_message()
```

**Comment by XM12G** [comment]
但我试了貌似不行……
刚翻了下源码貌似是post_messages()

**Comment by yanyongyu** [comment]
https://github.com/nonebot/adapter-qqguild/blob/d3e784f31643bee977bb6150ca8e9247cb87ab29/nonebot/adapters/qqguild/api/client.py#L147-L160
